apiVersion: v1
kind: ServiceAccount
metadata:
  name: workercontroller-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default # changer
  name: workercontroller-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workercontroller-role-binding
  namespace: default # changer
subjects:
  - kind: ServiceAccount
    name: workercontroller-account
    namespace: default # changer
roleRef:
  kind: Role
  name: workercontroller-role
  apiGroup: rbac.authorization.k8s.io
