apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - port: 8081
  selector:
    app: api
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/apidb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: harbor.fsa.os.univ-lyon1.fr/fsa/api:latest
          name: api
          ports:
            - containerPort: 8081
              name: api
          envFrom:
            - configMapRef:
                name: api-config
