apiVersion: v1
kind: Service
metadata:
  name: workercontroller
spec:
  ports:
    - port: 8082
      targetPort: 8080
  selector:
    app: workercontroller
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workercontroller
spec:
  selector:
    matchLabels:
      app: workercontroller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: workercontroller
    spec:
      containers:
        - image: harbor.fsa.os.univ-lyon1.fr/prj-15/workercontroller:latest
          name: workercontroller
          ports:
            - containerPort: 8080
              name: workerctrl
      imagePullSecrets:
        - name: harborcred
