apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  ports:
    - port: 8080
  selector:
    app: worker
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - image: harbor.fsa.os.univ-lyon1.fr/prj-15/worker:latest
          name: worker
          ports:
            - containerPort: 8080
              name: worker

        - livenessProbe:
            httpGet:
                path: /actuator/health
                port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          name: worker
      imagePullSecrets:
        - name: harborcred
